name: doalink
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.13.1
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  animate_do: ^4.2.0
  geolocator: ^14.0.2
  carousel_slider: ^5.1.1
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptative_icon_background: "#fffff"
  adaptative_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  #   Títulos principais: Playfair Display Bold

  # Subtítulos: Raleway Medium

  # Corpo de texto e UI geral: Funnel Sans Regular / Bold
  fonts:
    - family: Primary
      fonts:
        - asset: assets\fonts\PlayfairDisplay-Bold.ttf

    - family: Subtitles
      fonts:
        - asset: assets\fonts\Raleway-Medium.ttf

    - family: TextsBody Bold
      fonts:
        - asset: assets\fonts\FunnelSans-Bold.ttf
    - family: TextsBody
      fonts:
        - asset: assets\fonts\FunnelSans-Regular.ttf

  assets:
    - assets/images/
    - assets/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
